name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for Xcode

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Agree to Xcode license
      run: sudo xcodebuild -license accept

    - name: Install CocoaPods (if needed)
      run: |
        gem install cocoapods -v 1.12.1
        pod install --repo-update

    - name: Build
      run: xcodebuild build -workspace TrendingMovies.xcworkspace -scheme TrendingMovies -allowProvisioningUpdates -destination 'platform=iOS Simulator,name=iPhone 12'

    - name: Run Unit Tests
      run: xcodebuild test -workspace TrendingMovies.xcworkspace -scheme TrendingMovies -destination 'platform=iOS Simulator,name=iPhone 12'
