name: Build and Test

on:
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: xcode-actions/setup-xcode@v2
      with:
        xcode-version: 13  # Specify the Xcode version you want to use

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build and Test
      run: |
        xcodebuild -workspace TrendingMovies.xcworkspace -scheme TrendingMovies -destination 'platform=iOS Simulator,name=iPhone 13' build test

