name: Build and Test

on:
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for Xcode

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: 13.0  # Replace with your desired Xcode version

    - name: Install CocoaPods (if needed)
      run: |
        gem install cocoapods -v 1.10.0
        pod install --repo-update

    - name: Build
      run: xcodebuild build -workspace YourWorkspaceName.xcworkspace -scheme YourSchemeName

    - name: Run Unit Tests
      run: xcodebuild test -workspace TrendingMovies.xcworkspace -scheme TrendingMovies -destination 'platform=iOS Simulator,name=iPhone 12'

    # Add additional steps as needed for your project
